jobs:
  - name: integration
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ch
        trigger: true
        passed:
          - qa
      - get: al2-emr-ami
        trigger: true
        passed:
          - qa
      - get: emr-launcher-release
        trigger: true
        passed:
          - qa
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'integration'
