jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ch
        trigger: false
      - get: al2-emr-ami
        trigger: false
      - get: emr-launcher-release
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply-destroy ))
        params:
          TF_WORKSPACE: 'preprod'
